### ISSUE TITLE
Gültiger Pfad "|:das/ist/ein/Pfad:>" wird nicht akzeptiert

### ISSUE THREAD

**Issue by ferenc-hechler** [VollDerIdiot/TPS#3]
Im Testfall hier:

https://github.com/VollDerIdiot/TPS/blob/4a016b67944f6049119164f5dd738445378f6b18/Kompiler/testsrc/tps/kompiler/objekte/kompilieren/sourcenladen/TpstSourceLaderTest.java#L159-L160

wird versucht den Pfad "|:das/ist/ein/Pfad:>" einzulesen, er wird aber nicht akzeptiert.
Der Pfad enthält aber keine ungültigen Zeichen, trotzdem witd ein FalscheSourcenFehler mit folgender Meldung geworfen:

     '|:das/ist/ein/Pfad' ist kein Pfad! Ein Pfad darf keine ungüligen Zeichen enthalten!

**Comment by VollDerIdiot** [comment]
> Im Testfall hier:
> 
> https://github.com/VollDerIdiot/TPS/blob/4a016b67944f6049119164f5dd738445378f6b18/Kompiler/testsrc/tps/kompiler/objekte/kompilieren/sourcenladen/TpstSourceLaderTest.java#L159-L160
> 
> wird versucht den Pfad "|:das/ist/ein/Pfad:>" einzulesen, er wird aber nicht akzeptiert.
> Der Pfad enthält aber keine ungültigen Zeichen, trotzdem witd ein FalscheSourcenFehler mit folgender Meldung geworfen:
> 
> ```
>  '|:das/ist/ein/Pfad' ist kein Pfad! Ein Pfad darf keine ungüligen Zeichen enthalten!
> ```

Der Fehler wurde behoben.
  vorher wurde das Startzeichen für den Pfad mit übergeben ('|:') allerdings war dies kein gültiges Zeichen (enthält ':') und so wurde ein Fehler geworfen.
